name: Helm Lint
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CHART_DIR: .

jobs:
  helm_lint:
    name: Helm Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: helm lint ${{ env.CHART_DIR }}

      # - uses: stackrox/kube-linter-action@v1
      #  with:
      #    directory: .
